services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: aichmi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./aichmi_db/aichmi_ddl.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./aichmi_db/sample_data.sql:/docker-entrypoint-initdb.d/02-data.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: aichmi
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data: